# Generated by Django 5.1.4 on 2025-01-06 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hashtag_like_is_repost_post_hashtags_sharedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Hashtags',
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='api.hashtag'),
        ),
    ]
