# Generated by Django 5.1.4 on 2025-01-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_post_hashtags_post_tagged_users_post_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
